WITH CREATED_USER AS ( INSERT INTO TODOS.USERS (LOGIN, PASSWORD) VALUES ($1, $2) ON CONFLICT DO NOTHING RETURNING USER_ID ) INSERT INTO TODOS.TOKENS (
    USER_ID,
    DUE_TS
)
    SELECT
        USER_ID,
        $3
    FROM
        CREATED_USER RETURNING TOKEN_ID;